<h1>Página do Administrador</h1>



<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Manter Editais
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><a href="/application/edital/index">Ver/Alterar Todos os Editais</a></li>
    <li><a href="/application/edital/create">Criar Novo Edital</a></li>
  </ul>
</div>


<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Manter Usuários
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><a href="/application/index/index">Ver/Alterar Todos os Usuarios</a></li>
    <li><a href="/application/index/create">Criar Novo User</a></li>
  </ul>
</div>


<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Manter Proposta
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><a href="/application/proposta/index">Ver/Alterar Todas as Propostas</a></li>
    <li><a href="/application/proposta/create">Criar Nova Proposta</a></li>
  </ul>
</div>
