
<p>User page<strong><?php echo $this->username; ?></strong>


  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Manter Editais
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><a href="/application/edital/indexuser">Ver Todos os Editais</a></li>
    </ul>
  </div>


  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Manter Proponente
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><a href="/application/index/index">Ver/Alterar Todos os Proponentes</a></li>
      <li><a href="/application/index/create">Criar Novo Proponente</a></li>
    </ul>
  </div>


  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Manter Proposta
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <li><a href="/application/proposta/index">Ver/Alterar Todas as Propostas</a></li>
      <li><a href="/application/proposta/create">Criar Nova Proposta</a></li>
    </ul>
  </div>
