
<form name="form" method="POST" action="/application/index/create">
	<label>Nome</label>
	<input type="text" name="nome" />
	<br/>
	<label>Endereço</label>
	<input type="text" name="endereco" />
	<br/>
	<label>Cidade</label>
	<input type="text" name="cidade" />
	<br/>
	<label>Bairro</label>
	<input type="text" name="bairro" />
	<br/>
	<button class="btn btn-success" type="submit">Enviar</button>
</form>
